import pandas as pd
import os

# Load real training data
train_real = pd.read_csv("data/train_processed.csv")

# Load synthetic normal data generated by WCGAN
synthetic_normal = pd.read_csv("outputs/synthetic_normal.csv")

# Extract real attack samples only
real_attack = train_real[train_real['label'] == 1]

# Extract real normal samples only
real_normal = train_real[train_real['label'] == 0]

# Combine: real attack + real normal + synthetic normal
balanced_df = pd.concat([real_attack, real_normal, synthetic_normal], ignore_index=True)

# Shuffle dataset
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Save to CSV
os.makedirs("data", exist_ok=True)
balanced_df.to_csv("data/train_balanced.csv", index=False)
print("✅ Balanced training dataset created at data/train_balanced.csv")
